SELECT * FROM northwind.customers;
SELECT distinct country from northwind.customers;
select * from customers where CustomerID like 'BL%';
select * from orders LIMIT 100;
select * from customers where postalcode in ('1010', '3012', '12209', '05023');
select * from orders where shipregion is not null;
select * from customers order by country, city;
insert into customers (CompanyName, CustomerID, ContactName, Country, Phone) value ('The Harbor', '88', 'Boaty McBoatface', 'England', '8675309');
update orders set shipregion='EuroZone' where shipcountry = 'France';
set sql_safe_updates = 0;
delete from `order details` where quantity = 1;
select MAX(quantity), min(quantity),  avg(quantity)  from `order details`;
select MAX(quantity), min(quantity),  avg(quantity)  from `order details` group by orderid;
select customerid from orders where orderid = '10290';
select * from customers JOIN orders on customers.CustomerID = orders.customerid;
select * from customers LEFT JOIN orders on customers.CustomerID = orders.customerid;
select * from customers RIGHT JOIN orders on customers.CustomerID = orders.customerid;
select * from employees where reportsto is null;
select FirstName from employees where reportsto = (select employeeid from employees where FirstName = 'Andrew');
